export const POLICY_SECTIONS = [
  { title: "1. Registration Fee", body: "Every student is required to pay the Registration Fee of GHS 200 before reporting to the hostel. This fee secures your spot and covers administrative onboarding. Payment must be made via bank transfer or Mobile Money to the accounts listed in your Fees & Payments page. Use your Student ID as the payment reference at all times." },
  { title: "2. Hostel Fee", body: "The annual Hostel Fee of GHS 4,500 covers your accommodation for the full academic year. Payment may be made in full or in approved installments. Failure to settle the full balance by the published deadline may result in suspension of hostel privileges." },
  { title: "3. Check-In and Check-Out", body: "Students must check in upon arrival and check out before leaving the hostel for extended periods. The Student Portal provides a one-tap Check In and Check Out button. Curfew is 10:00 PM on weekdays and 11:00 PM on weekends." },
  { title: "4. Electricity (Meter Usage)", body: "Each room is grouped under a shared electricity meter. Excessive use of high-load appliances (heaters, electric stoves, irons left on) is not permitted. Tampering with the meter is a serious offense and grounds for immediate eviction." },
  { title: "5. Noise & Conduct", body: "Quiet hours are observed daily between 10:00 PM and 6:00 AM. Loud music, parties, and disorderly behavior are prohibited. Treat fellow students and staff with respect at all times." },
  { title: "6. Room Maintenance", body: "Keep your room and shared spaces clean. Report any damage, leaks, faulty bulbs, or pest issues through the hostel management or your Profile contact channels. Do not paint, drill, or modify the room without written permission." },
  { title: "7. Visitors", body: "Visitors are allowed between 10:00 AM and 8:00 PM and must sign in at the front desk. Overnight guests are not permitted unless pre-approved by management. The host student is responsible for the conduct of any visitor." },
  { title: "8. Communication & WhatsApp", body: "Official announcements are sent via SMS and the hostel WhatsApp group. You must keep your phone number and WhatsApp number on the system up to date. Ignoring official communications is not an excuse for non-compliance." },
  { title: "9. Store Purchases", body: "The on-site Hostel Store accepts orders through the Student Portal on a pay-on-delivery basis. Place clear orders, be available to receive your items, and settle the bill on delivery. Repeated failure to collect orders may result in store restrictions." },
  { title: "10. Compliance", body: "By accepting these policies you agree to abide by all rules of SME Hostels and the published University regulations. Breach of these policies may result in warnings, fines, suspension of hostel privileges, or eviction. Management reserves the right to update these policies; students will be notified of any changes via SMS and WhatsApp." },
];
