/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentHomeRouteImport } from './routes/student-home'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PaymentCallbackRouteImport } from './routes/payment-callback'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const StudentHomeRoute = StudentHomeRouteImport.update({
  id: '/student-home',
  path: '/student-home',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment-callback',
  path: '/payment-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/policy': typeof PolicyRoute
  '/portal': typeof PortalRoute
  '/setup': typeof SetupRoute
  '/student-home': typeof StudentHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/policy': typeof PolicyRoute
  '/portal': typeof PortalRoute
  '/setup': typeof SetupRoute
  '/student-home': typeof StudentHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/onboarding': typeof OnboardingRoute
  '/payment-callback': typeof PaymentCallbackRoute
  '/policy': typeof PolicyRoute
  '/portal': typeof PortalRoute
  '/setup': typeof SetupRoute
  '/student-home': typeof StudentHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/onboarding'
    | '/payment-callback'
    | '/policy'
    | '/portal'
    | '/setup'
    | '/student-home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/onboarding'
    | '/payment-callback'
    | '/policy'
    | '/portal'
    | '/setup'
    | '/student-home'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/onboarding'
    | '/payment-callback'
    | '/policy'
    | '/portal'
    | '/setup'
    | '/student-home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  OnboardingRoute: typeof OnboardingRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PolicyRoute: typeof PolicyRoute
  PortalRoute: typeof PortalRoute
  SetupRoute: typeof SetupRoute
  StudentHomeRoute: typeof StudentHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-home': {
      id: '/student-home'
      path: '/student-home'
      fullPath: '/student-home'
      preLoaderRoute: typeof StudentHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-callback': {
      id: '/payment-callback'
      path: '/payment-callback'
      fullPath: '/payment-callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  OnboardingRoute: OnboardingRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PolicyRoute: PolicyRoute,
  PortalRoute: PortalRoute,
  SetupRoute: SetupRoute,
  StudentHomeRoute: StudentHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
